services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trento_backend
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trento_frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    # --- INICIO DE LA MODIFICACIÓN ---
    environment:
      - INTERNAL_API_URL=http://backend:3000
    # --- FIN DE LA MODIFICACIÓN ---
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    restart: unless-stopped
  
  # ... (resto de los servicios postgres y redis)
  postgres:
    image: postgres:14-alpine
    container_name: trento_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: trento_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: